### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by ayozealfageme** [S120/PKSFC#2]
How can I solve the following problem? Thanks in advance

> install.packages("pathtomyfolder",repos = NULL, type="source")
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning: invalid package 'C:/Users/USER~1/DOCUME~1/G'
Error: ERROR: no packages specified
"D" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Warning messages:
1: comando ejecutado '"C:/PROGRA~1/R/R-32~1.4RE/bin/x64/R" CMD INSTALL -l "C:\Users\USER\Documents\R\win-library\3.2" "C:/Users/USER~1/DOCUME~1/G&D/PKSFC-~1/PKSFC_1.5.tar.gz"' tiene estatus 1 
2: In install.packages("C:\\Users\\USER\\Documents\\G&D\\PKSFC-master/PKSFC_1.5.tar.gz",  :
  installation of package ‘C:/Users/USER~1/DOCUME~1/G&D/PKSFC-~1/PKSFC_1.5.tar.gz’ had non-zero exit status

**Comment by antoinegodin** [comment]
Hi, could you give me a bit more details on what you tried to do? It is difficult to read the thread without knowing what command you tried to execute. From what I read it looks like you did not specify the path correctly when trying to install the PKSFC package.

**Comment by ayozealfageme** [comment]
Hello, thanks for attending my request.

I attach a screenshot with the message from Rstudio and the folder where the package is stored. If something else is required please let me know.

Thanks!
![error](https://cloud.githubusercontent.com/assets/26234373/23994684/5cf56dac-0a46-11e7-9bbc-8ee666e64aeb.png)

**Comment by antoinegodin** [comment]
I think it has to do with the & into the path. Could you remove the '&' in the file name? The other solution would be to change the working directory to the folder containing the .tar.gz and just use a relative path:

`setwd("pathToYourDirectory")`
`install.packages("PKSFC_1.5.tar.gz",repos=NULL, type="source)`

 instead of absolute path.
