### ISSUE TITLE
Implementing binary variables and If-functions in a model

### ISSUE THREAD

**Issue by TheMKVL** [S120/PKSFC#4]
Dear fellow PKSFC-users,

How can I implement a variable (in a model-txt file), that takes the value 1 given some constraint and else 0? A well known example would be the implementation of a checking account balances being negative as in Godley and Lavoie (2006) Monetary Economics p. 330 (second edition):

`M1h = M1hN * z1
z1 = 1 iff M1hN >= 0`

The tutorials do not cover such cases and I am not entirely sure if the sfc.model() function is capable of implementing if-functions.

Thanks in advance.

**Comment by antoinegodin** [comment]
Hi TheMKVL,

You can use 'ifelse' functions in the source code of your model. In your case it would look like this:

`M1h = ifelse(M1hN>=0,M1hN,0)`

Note that you could also use 'min' or 'max' functions as well, depending on the usage. In you case, it would look like this:

`M1h = max(M1hN,0)`

Further note that, if you do use these functions, your model becomes non-linear and if you have a simultaneous system of non-linear equations, the Gauss-Seidel algorithm (the only numerical solver implemented in he package) is not guaranteed to converge. So you should be careful when you use these functions.

I hope this helps.

**Comment by TheMKVL** [comment]
Dear Prof. Godin,

Thanks for the solution. I used this command to built a somewhat bigger (~50 equation) model, that I wanted to numerically simulate (not estimate). However, and I think that somehow relates to your last comment, it becomes rather tedious to solve such a model. In the Tutorials for SIM and SIMEX, the models start from a state where there is no economic activity. Starting values are zero, which is pretty convenient.

With more complex models this does not seem to work anymore (this is also the case in the Tutorial for PC). After setting up the accounting identities and behavioural equations, I seem to be stuck with defining starting values. So far, whenever I have determined values, e.g. by using sensible stock-flow ratios, the model showed explosive behaviour when simulating. Now, I am not entirely sure if this is the reason because I chose these values erroneously (very likely) or because the model contains non-linearities. 

I feel like, I have replicated the problem, which you mention in your paper with Stephen Kinsella and G. Tiou Tagba Aliti from 2012 on estimation of PKSFC Models:

First you argue:
"Most equations are linear [which does not seem to be the case anymore], so stock-flow consistent models can normally be solved for their steady state [which I already seem to struggle with], and the behavior of the system can be analyzed and discussed in comparison with a baseline or series of baselines"

and:

"Finding stock flow norms is, at present, a black art, and more error than trial is involved in finding them"

My essential question would then be: Is there some possibility to conveniently define starting values using the PKSFC Package (without using real world data)? If not: is there any other reasonable way, which allows me to at least eliminate the possibility that my inability in defining initial values is the reason for the explosive behaviour?

Apologies for the long text!

**Comment by antoinegodin** [comment]
Dear TheMKVL,

Unfortunately, there is no easy solution for your question. Have a look at [this seminar](https://github.com/antoinegodin/SFC_lectures/blob/master/Slides%20and%20Readings/SeminarFinal.pdf) I did with my MA students in Kingston. You might find something that helps you. Look also in the [module folder](https://github.com/antoinegodin/SFC_lectures), you might find more information.
